CREATE TABLE [dbo].[ASPNETUSERLOGINS] (
    [LoginProvider] NVARCHAR (128) NOT NULL,
    [ProviderKey]   NVARCHAR (128) NOT NULL,
    [UserId]        NVARCHAR (128) NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_UserId]
    ON [dbo].[ASPNETUSERLOGINS]([UserId] ASC);


GO
ALTER TABLE [dbo].[ASPNETUSERLOGINS]
    ADD CONSTRAINT [PK_dbo.ASPNETUSERLOGINS] PRIMARY KEY CLUSTERED ([LoginProvider] ASC, [ProviderKey] ASC, [UserId] ASC);


GO
ALTER TABLE [dbo].[ASPNETUSERLOGINS]
    ADD CONSTRAINT [FK_dbo.ASPNETUSERLOGINS_dbo.ASPNETUSERS_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[ASPNETUSERS] ([Id]) ON DELETE CASCADE;