CREATE TABLE [dbo].[ASPNETROLES] (
    [Id]   NVARCHAR (128) NOT NULL,
    [Name] NVARCHAR (256) NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RoleNameIndex]
    ON [dbo].[ASPNETROLES]([Name] ASC);


GO
ALTER TABLE [dbo].[ASPNETROLES]
    ADD CONSTRAINT [PK_dbo.ASPNETROLES] PRIMARY KEY CLUSTERED ([Id] ASC);