
CREATE TABLE [dbo].[ASPNETUSERROLES] (
    [UserId] NVARCHAR (128) NOT NULL,
    [RoleId] NVARCHAR (128) NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_UserId]
    ON [dbo].[ASPNETUSERROLES]([UserId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_RoleId]
    ON [dbo].[ASPNETUSERROLES]([RoleId] ASC);


GO
ALTER TABLE [dbo].[ASPNETUSERROLES]
    ADD CONSTRAINT [PK_dbo.ASPNETUSERROLES] PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC);


GO
ALTER TABLE [dbo].[ASPNETUSERROLES]
    ADD CONSTRAINT [FK_dbo.ASPNETUSERROLES_dbo.ASPNETROLES_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[ASPNETROLES] ([Id]) ON DELETE CASCADE;


GO
ALTER TABLE [dbo].[ASPNETUSERROLES]
    ADD CONSTRAINT [FK_dbo.ASPNETUSERROLES_dbo.ASPNETUSERS_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[ASPNETUSERS] ([Id]) ON DELETE CASCADE;


