
CREATE TABLE [dbo].[ASPNETUSERCLAIMS] (
    [Id]         INT            IDENTITY (1, 1) NOT NULL,
    [UserId]     NVARCHAR (128) NOT NULL,
    [ClaimType]  NVARCHAR (MAX) NULL,
    [ClaimValue] NVARCHAR (MAX) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_UserId]
    ON [dbo].[ASPNETUSERCLAIMS]([UserId] ASC);


GO
ALTER TABLE [dbo].[ASPNETUSERCLAIMS]
    ADD CONSTRAINT [PK_dbo.ASPNETUSERCLAIMS] PRIMARY KEY CLUSTERED ([Id] ASC);


GO
ALTER TABLE [dbo].[ASPNETUSERCLAIMS]
    ADD CONSTRAINT [FK_dbo.ASPNETUSERCLAIMS_dbo.ASPNETUSERS_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[ASPNETUSERS] ([Id]) ON DELETE CASCADE;


