CREATE TABLE [dbo].[FILESPEC] (
    [Id]        INT          IDENTITY (1, 1) NOT NULL,
    [DataItem]  VARCHAR (50) NULL,
    [NoOfBytes] INT          NULL,
    [RowType]   VARCHAR (1)  NULL,
    [SetA]      BIT          NULL,
    [SetAPos]   INT          NULL,
    [SetB]      BIT          NULL,
    [SetBPos]   INT          NULL,
    [SetC]      BIT          NULL,
    [SetCPos]   INT          NULL,
    [SetD]      BIT          NULL,
    [SetDPos]   INT          NULL,
    [SetE]      BIT          NULL,
    [SetEPos]   INT          NULL,
    [SetF]      BIT          NULL,
    [SetFPos]   INT          NULL,
    [SetG]      BIT          NULL,
    [SetGPos]   INT          NULL,
    [SetH]      BIT          NULL,
    [SetHPos]   INT          NULL,
    [SetI]      BIT          NULL,
    [SetIPos]   INT          NULL,
    [SetJ]      BIT          NULL,
    [SetJPos]   INT          NULL,
    [SetK]      BIT          NULL,
    [SetKPos]   INT          NULL,
    [SetL]      BIT          NULL,
    [SetLPos]   INT          NULL,
    [SetM]      BIT          NULL,
    [SetMPos]   INT          NULL,
    [SetN]      BIT          NULL,
    [SetNPos]   INT          NULL,
    CONSTRAINT [PK__tmp_ms_x__3214EC07CE7C7041] PRIMARY KEY CLUSTERED ([Id] ASC)
);

