CREATE TABLE [dbo].[TRANSACTIONSPOLICYHOLDER]
(
	[TransactionNo] VARCHAR(15) NOT NULL , 
    [FullName] NVARCHAR(150) NULL, 
    [NRICFIN] VARCHAR(15) NULL, 
    [Email] NVARCHAR(50) NULL, 
    [Mobile] VARCHAR(50) NULL, 
    [DateOfBirth] DATE NULL, 
    [Gender] VARCHAR(10) NULL, 
    CONSTRAINT [PK_TRANSACTIONSPOLICYHOLDER] PRIMARY KEY ([TransactionNo])
)
